version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: medical-platform-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medical_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: medical-platform-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_USER: postgres
      DB_HOST: postgres
      DB_NAME: medical_platform
      DB_PASSWORD: postgres
      DB_PORT: 5432
      PORT: 5000
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET:-change-this-secret-in-production}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:3000}
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/usr/src/app/logs
    restart: unless-stopped

volumes:
  postgres_data:
